create or replace TABLE CRYPTO.BINANCE.DATA_TRACKS cluster by (SYMBOL, EVENT_TIME)(
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL,
	SYMBOL VARCHAR(20) NOT NULL,
	KLINE_START_TIME TIMESTAMP_NTZ(9),
	KLINE_CLOSE_TIME TIMESTAMP_NTZ(9),
	OPEN_PRICE FLOAT,
	CLOSE_PRICE FLOAT,
	HIGH_PRICE FLOAT,
	LOW_PRICE FLOAT,
	IGNORE_FIELD VARCHAR(16777216),
	primary key (EVENT_TIME, SYMBOL),
	foreign key (EVENT_TIME, SYMBOL) references CRYPTO.BINANCE.STATE_TRACKS(EVENT_TIME,SYMBOL)
);

create or replace TABLE CRYPTO.BINANCE.STATE_TRACKS (
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL,
	SYMBOL VARCHAR(20) NOT NULL,
	IS_KLINE_CLOSED BOOLEAN NOT NULL,
	primary key (EVENT_TIME, SYMBOL)
);

create or replace TABLE CRYPTO.BINANCE.TRADE_TRACKS cluster by (SYMBOL, EVENT_TIME)(
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL,
	SYMBOL VARCHAR(20) NOT NULL,
	FIRST_TRADE_ID NUMBER(38,0),
	LAST_TRADE_ID NUMBER(38,0),
	BASE_ASSET_VOLUME FLOAT,
	NUMBER_OF_TRADES NUMBER(38,0),
	QUOTE_ASSET_VOLUME FLOAT,
	TAKER_BUY_BASE_ASSET_VOLUME FLOAT,
	TAKER_BUY_QUOTE_ASSET_VOLUME FLOAT,
	primary key (EVENT_TIME, SYMBOL),
	foreign key (EVENT_TIME, SYMBOL) references CRYPTO.BINANCE.STATE_TRACKS(EVENT_TIME,SYMBOL)
);